[tool.poetry]
name = "driver"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "3.8"
colored = "*"
numpy = "*"
scipy = "*"
scikit-learn = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
